### PR TITLE
Update to Chrome 55.0.2883.75

### PR DESCRIPTION
**Pull request by seangerhardt-wf**
Problem: Old Chrome

Solution: Update to Chrome 55

Leo, there may be a lot of steps I'm missing. I simply looked for references to chrome 54 and updated them with hopes the build process would work it's magic. 

I'm hoping to learn all the steps needed here so that I could help with this in future releases.

### CODE REVIEW

**Comment by elgalu** [comment]
LGTM. You still need to sign the CLA. The failed test is a flaky test that I need to improve (sometimes the python selenium test halts then Travis timeouts)

**Comment by seangerhardt-wf** [comment]
Sounds good - let me know if there's anything else I need to do.

**Comment by seangerhardt-wf** [comment]
@elgalu Do you know when I can expect this change in a release? I'm not sure what the criteria is for making a release.

**Comment by elgalu** [comment]
For now the criteria is that I have to manually trigger the release, should be done soon:
https://travis-ci.org/elgalu/docker-selenium/builds/183296250

**Pull request merged**
