### PR TITLE
Generic cleanup

### PR DESCRIPTION
**Pull request by TobiX**
These are some suggestions, mainly to get some discussion going :smile_cat:

I think having a more "maintainable" Dockerfile would lower the barrier for external contributors, so here are some minor "clean-up" suggestions:

- Get rid of all those size comments, so nobody has to break a sweat updating them
- Use a newer Ubuntu base (maybe update to bionic next?)
- The dockerfile did really strange stuff with the sources.list & apt-key, I just got rid of that
- libav isn't in Ubuntu anymore, focus on ffmpeg
- OpenJDK is just fine, remove mentions of Oracle Java
- Remove haveged - I don't think it adds anything worthwhile and the other Java workaround is quite sufficient IMHO (see also https://www.2uo.de/myths-about-urandom/)

I don't expect this to be merged without comment, so: Roast me!

PS: I would even suggest to go quite a bit further with the clean-up: Currently, there are 13 steps which use apt to install packages. I would suggest joining them in one big step (layer) and move all the configuration after that. That would also make it easier to unify the use of `--no-install-recommends`, which is currently missing in some places, which probably also bloats the image a bit.

### CODE REVIEW

**Comment by elgalu** [comment]
Nice! thanks! if the build passes I think we can merge<3

**Comment by elgalu** [comment]
:+1:

**Comment by TobiX** [comment]
> if the build passes I think we can merge

Sure, if you are fine with all my changes :+1:

**Comment by elgalu** [comment]
let's wait a bit to see if @diemol remembers something about those issues else I think we can merge.

**Comment by diemol** [comment]
Honestly, all the changes affect code that was there even before I started helping with the repo, probably all added by @elgalu, so if he is fine with it, I am fine as well.

I would only ask, if @TobiX,  could stick around after the following releases, in case something does not work and we need some help to debug it and fix it.

**Comment by TobiX** [comment]
> I would only ask, if @TobiX, could stick around after the following releases, in case something does not work and we need some help to debug it and fix it.

We're actively using this image, so I should be able to notice any problems 😅

**Pull request merged**
