### PR TITLE
Chrome startup script parsing when passing user-agent

### PR DESCRIPTION
**Pull request by AdeelKhurshid-minted**
Causes Chrome to start up with multiple tabs and no honor user-agent sent in by the selenium driver.

image

### CODE REVIEW

**Comment by AdeelKhurshid-minted** [comment]
I see notes about finicky builds so I assume thats the case here.

**Comment by elgalu** [comment]
Thanks @AdeelKhurshid-minted your fix looks correct, I've restarted the builds and will take a look into this probably next week.

**Comment by elgalu** [comment]
@AdeelKhurshid-minted I'm pretty sure your fix is correct. I've restarted the job 5 times or more already and it always fails with Docker version 1.12.2-rc1 + Docker compose 1.8.0 but I can't see how that can be related to this fix. Master is passing ok.

Anyway I'll work to figure out the problem, can you write here how are you passing the user-agent so I can add some tests to the suite? Is is through `-e CHROME_ARGS` or you do it through you selenium source code? Please paste it, thanks.

**Comment by AdeelKhurshid-minted** [comment]
@elgalu I am using webdriver.io  version "4.2.8". 

In my wdio.conf.js I have:

var chromeopts = [];
if (process.env_MOBILEBROWSER || process.env.MOBILEBROWSER) {
    deviceopts = { deviceName: 'Google Nexus 5'};
}
.....
    capabilities: [{
        browserName: "chrome",
        version: "*",
        platform: "LINUX",
        chromeOptions: {
             args: chromeopts,
             mobileEmulation: deviceopts
        }
    }],

**Comment by elgalu** [comment]
Can you sign the [licence/cla](https://cla-assistant.io/elgalu/docker-selenium?pullRequest=123) ?

**Comment by AdeelKhurshid-minted** [comment]
Signed. Thanks.

**Comment by elgalu** [comment]
Thanks, merged! I also added [some mobileEmulation tests](https://github.com/elgalu/docker-selenium/blob/0d32cfab08b3bbbd20bf84714cf99af078f45d4c/test/python_test.py#L27)

image

Sample video:
https://youtu.be/CwVIbd-2iHI

**Pull request merged**
