### PR TITLE
Selenium 3.4.0

### PR DESCRIPTION
**Pull request by SrinivasanTarget**

### CODE REVIEW

**Comment by diemol** [comment]
We have been trying to upgrade during this week wiht @elgalu but the tests are not passing, we are also upgrading Geckodriver and Firefox... Since it is strongly recommended to use Geckodriver 0.16 with Selenium 3.4.0
Any help tuning the image is appreciated.

**Comment by SrinivasanTarget** [comment]
yup heard about the firefox crash with old versions @diemol Will look into it further.

**Comment by elgalu** [comment]
Hi, thanks for contributing @SrinivasanTarget !

As Diego mentioned we haven't been able to upgrade because the selenium python tests are failing, even when upgrading the requirements.txt to use selenium 3.4.0 python bindings, it just halts at `Will connect to selenium at http://127.0.0.1:24444/wd/hub`

**Comment by SrinivasanTarget** [comment]
Yes @elgalu Unfortunately not enough logs to debug. Is it something to do with python version we use? i didn't give a try in python 3+.

**Comment by elgalu** [comment]
I'm using python 3.5.2, I will try 3.6.1 later on but I think the problem is more python bindings related or perhaps an API change, this is the current python test that's failing:
https://github.com/elgalu/docker-selenium/blob/master/test/python_test.py

**Comment by SrinivasanTarget** [comment]
Yes I did had a look at the test here https://github.com/elgalu/docker-selenium/blob/master/test/python_test.py#L52 but was not able to figure out :(

**Comment by elgalu** [comment]
So you can reproduce the error locally?

**Comment by SrinivasanTarget** [comment]
@elgalu Nope i havent tried it locally.. will try it

**Comment by elgalu** [comment]
Maybe it gets fixed with the new version they released today 3.4.2 see https://pypi.python.org/pypi/selenium

**Comment by elgalu** [comment]
stills fails

**Comment by elgalu** [comment]
Selenium 3.5.0 was released but still has the same issues.

**Comment by elgalu** [comment]
I tried latest Selenium 3.5.2 and it doesn't seem to like some of our custom grid capabilities, as can be seen in this logs:

```
/var/log/cont/selenium-hub-stderr.log:15:11:18.605 INFO - Nodes should register to http://172.17.0.3:24444/grid/register/ /var/log/cont/selenium-hub-stderr.log:15:11:18.605 INFO - Selenium Grid hub is up and running /var/log/cont/selenium-hub-stderr.log:15:11:19.419 INFO - Registered a node http://127.0.0.1:25550 /var/log/cont/selenium-hub-stderr.log:15:11:19.419 INFO - Registered a node http://127.0.0.1:25551 /var/log/cont/selenium-hub-stderr.log:15:11:24.581 INFO - Mismatched capabilities. Creating a synthetic w3c capability. /var/log/cont/selenium-hub-stderr.log:15:11:24.584 INFO - Got a request to create a new session: Capabilities [{build=dosel, recordVideo=false, tunnel-identifier=zalenium, name=test-adwords, browserName=chrome, screenResolution=1900x1880, platformName=ANY, version=, platform=ANY}] /var/log/cont/selenium-hub-stderr.log:15:11:24.585 INFO - Trying to create a new session on test slot {chrome_binary=/usr/bin/google-chrome-stable, seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1900x1880, tz=Europe/Berlin, browserName=chrome, maxInstances=1, screenResolution=1900x1880, resolution=1900x1880, version=60.0.3112.101, platform=LINUX} /var/log/cont/selenium-hub-stderr.log:15:11:24.587 ERROR - Error running the beforeSessionListener : null /var/log/cont/selenium-hub-stderr.log:java.lang.UnsupportedOperationException
```

**Comment by elgalu** [comment]
Finally managed to upgrade to 3.4.0, see branch: https://github.com/elgalu/docker-selenium/tree/3.4.0

Users can pull 3.4.0 [image](https://hub.docker.com/r/elgalu/selenium/tags/): `docker pull elgalu/selenium:3.4.0`

However latest wasn't affect as we want to move latest only for 3.5.3 which this fixed: https://github.com/SeleniumHQ/selenium/issues/3808#issuecomment-321826470

**Pull request closed without merging**
