### PR TITLE
update chrome and driver to 87

### PR DESCRIPTION
**Pull request by ewul**

### CODE REVIEW

**Comment by baflQA** [comment]
@ewul can You pls sign the license?

**Comment by ewul** [comment]
Re-pushed and signed. @baflQA

**Review by diemol — APPROVED** [review]
Thank you, @ewul!

**Comment by ewul** [comment]
Could you please release the docker with chrome 87 to hub. I could not build the docker locally because I can't touch google inside China. Thanks. @diemol @baflQA @TobiX

**Comment by diemol** [comment]
The release happens automatically, this is the Travis job doing it https://travis-ci.org/github/elgalu/docker-selenium/builds/744837861
Seems to be queued for now. Let's wait for Travis.

**Comment by ewul** [comment]
That's very well. Thank you. @diemol

**Pull request merged**
