### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gomezgoiri**

### CODE REVIEW

**Comment by elgalu** [comment]
Thanks!!

**Comment by elgalu** [comment]
@gomezgoiri this is kind of retro-active, could you please sign the [licence/cla](https://cla-assistant.io/elgalu/docker-selenium?pullRequest=44) this is a new requirement related for example to ensure you didn't take this code from a third party and boring legal stuff like that, you can read it all by following the link, thanks!

**Comment by gomezgoiri** [comment]
I understand that this is an automatic message, but sorry, I won't authorize any third-party application to access my private email address for such a insignificant markdown formating issue as this.

**Comment by elgalu** [comment]
Is ok, I'm not a lawyer but my I guess is: it doesn't matter in this case.

**Pull request merged**
