### PR TITLE
Testing malicious pull request

### PR DESCRIPTION
**Pull request by diemol**
Testing if a pull request containing malicious code could print Travis' encrypted variables.

### CODE REVIEW

**Comment by elgalu** [comment]
Good point, looks like Travis hides the secret output somehow

**Comment by elgalu** [comment]
Thanks @diemol so works like this, for pull requests the secret env vars are not even set but for repo owners PRs it does, e.g.

```sh
$ export DOCKER_EMAIL=[secure]
$ export DOCKER_USERNAME=[secure]
$ export DOCKER_PASSWORD=[secure]
$ export GH_TOKEN=[secure]
```

**Comment by elgalu** [comment]
@diemol this is kind of retro-active, could you please sign the [licence/cla](https://cla-assistant.io/elgalu/docker-selenium?pullRequest=73) this is a new requirement related for example to ensure you didn't take this code from a third party and boring legal stuff like that, you can read it all by following the link, thanks!

**Comment by diemol** [comment]
Done!

**Pull request closed without merging**
