### PR TITLE
Add browsermob-proxy in run supervisor

### PR DESCRIPTION
**Pull request by jlamaille**
To be able to manipulate headers, filter urls and see performance, I would like to add browser mob proxy to the image

### CODE REVIEW

**Comment by elgalu** [comment]
Hi! thanks for your contribution! could you download the JAR during docker build instead of committing it to the project?

**Comment by jlamaille** [comment]
indeed, it will be much cleaner, I just push the fix

**Comment by baflQA** [comment]
Hey guys! Can You pls provide some example on how to run the BrowserMob on the image?

**Comment by jlamaille** [comment]
> Hey guys! Can You pls provide some example on how to run the BrowserMob on the image?

Hey,
To launch a selenium node with the process browsermob proxy, you must type:
docker run -e BROWSERMOBPROXY_START=true selenium
Then on the container if you can handle the proxy:
curl localhost:8080 / proxy
You can change the port with the following environment variable:
ENV_BROWSERMOBPROXY_PORT
It may be necessary to work on exposed port but I did not need it because i work in parallel on the zalenium project to integrate a manipulation of the light proxy directly with the capabilities

**Pull request merged**
